import { z } from 'zod';

export const createGoalSchema = z.object({
  companyBranchId: z.coerce.number().int().positive(),
  month: z.coerce.number().int().min(1).max(12),
  year: z.coerce.number().int().min(1900),
  productRevenue: z.coerce.number().default(0),
  serviceRevenue: z.coerce.number().default(0),
  ticketAverage: z.coerce.number().default(0),
  customers: z.coerce.number().int().min(0).default(0),
  newCustomers: z.coerce.number().int().min(0).default(0),
  productsPerClient: z.coerce.number().min(0).default(0),
  servicesPerClient: z.coerce.number().min(0).default(0),
  marketing: z.coerce.number().default(0),
  leadsGenerated: z.coerce.number().int().min(0).default(0),
  leadsMeetings: z.coerce.number().int().min(0).default(0),
  marketingSales: z.coerce.number().int().min(0).default(0),
  cpl: z.coerce.number().min(0).default(0),
  leadToMeetingRate: z.coerce.number().min(0).max(100).default(0),
  meetingToSaleRate: z.coerce.number().min(0).max(100).default(0),
  roas: z.coerce.number().min(0).default(0),
  redFlagPercentage: z.coerce.number().min(0).max(100).default(0),
  yellowFlagPercentage: z.coerce.number().min(0).max(100).default(0),
  greenFlagPercentage: z.coerce.number().min(0).max(100).default(0),
});
